
install_data('feed-64.png',
  install_dir : join_paths(get_option('libdir'), 'budgie-desktop', 'plugins', 'discovery-applet', 'resources', 'icons')
)

install_data('chatgpt-64.png',
  install_dir : join_paths(get_option('libdir'), 'budgie-desktop', 'plugins', 'discovery-applet', 'resources', 'icons')
)

install_data('apps-64.png',
  install_dir : join_paths(get_option('libdir'), 'budgie-desktop', 'plugins', 'discovery-applet', 'resources', 'icons')
)

install_data('weather-64.png',
  install_dir : join_paths(get_option('libdir'), 'budgie-desktop', 'plugins', 'discovery-applet', 'resources', 'icons')
)